---
title: "Vi er Team TADA"
subtitle: "*Trygg AI og DataAnalyse*"
toc: false
#lang: fr
#image: images/tada-logos/logo_utenbg_m_tada.svg
fig-format: svg
about: 
    template: marquee
    image-shape: round
    #image-width: 20em
    image-alt: "TADA-logo med en svingende tryllestav som tegner omrisset i form av et juridisk paragraftegn, og etterlater seg et spor av fem glitrende stjerner."   
---

[TADA](https://teamkatalog.nav.no/team/faad3209-800e-44ed-8fc2-cde6eba69f1c) [støtter](https://teamtopologies.com/key-concepts) ansvarlig KI og data science i Nav.

Vi er ansvarlige for Navs [prinsipper for ansvarlig KI](https://aksel.nav.no/god-praksis/artikler/prinsipper-for-ansvarlig-ki-i-nav), og for tilby rettledning, samt å bistå i vurderinger av hvordan prinsippene can etterleves i praksis.

Vi gir tilbakemeldinger, veiledning og teknisk bistand, i tillegg til å bidra til utforming av policy og styringsrammeverk. Vi holder oss oppdatert på trender innen AI/ML og datavitenskap ved å samarbeide med forskningsinstitusjoner, delta på konferanser og meetups, og utforske ny teknologi og metoder – og deler det vi lærer både internt og eksternt i Nav.

## Hva jobber vi med høsten 25?

- Navs pilot av M365 Copilot
- Analyse av NKS-løsningen "Bob" opp mot Navs prinsipper for ansvarlig KI. 
- Ferdigstille [analyse](https://data.ansatt.nav.no/quarto/a88016a5-d1f6-4702-b865-e668839538c3/index.html) av løsningen [Superrask Søknad](https://arbeidsplassen.nav.no/superrask-soknad-person)
- Inspill til Navs høringssvar til [høring til utkast til ny lov om kunstig intelligens](https://www.regjeringen.no/no/dokumenter/3112327/id3112327/)
– Deltar og bistår i kjernegruppen som utarbeider et styringssystem for kunstig intelligens i Nav.
- Utvikling av verktøy for avhjelpe team med å forstå sine forpliktelser ifm KI-forordningen
– Planlegge TADAgen 10. november med fokus på krav til språkmodeller i offentlig forvaltning.
– Denne hjemmesiden…

## Noe du lurer på eller noe vi kan hjelpe med?
- Ta kontakt på [Slack.](https://nav-it.slack.com/archives/C03CXENSLMV)
