---
title: "Prosjekter"
---

## Modellkort

Et [modellkort](https://arxiv.org/abs/1810.03993) er et kort, standardisert dokument inneholder nøkkelinformasjon om en maskinlæringsmodell. Hensikten er å gjøre modellens egenskaper, begrensninger og etiske fotavtrykk tydelige, og legge tilrette for ansvarlig bruk og enklere styring.

Modellkort kan bidra til:

* **Åpenhet**: Interessenter kan raskt forstå modellens tiltenkte formål, egenskaper ved treniningsdata, hvilke tester og vurderinger som er gjort, utfalle av disse, samt kjente begrensninger ved modellen.
* **Ansvarlighet**: Strukturert informasjon om hvordan modellen er utviklet og blitt til, forenkler revisjon og etterlevelse.
* **Sikkerhet**: Ved å synliggjøre bias-målinger, feilscenarier og etiske vurderinger, kan modellkort bidra til å redusere utilsiktet skade.

Modellkort anbefales som et styringsverktøy. TADA utforsker [praktisk nytte og utfordringer ved realisering](kortstokken) i Nav. 

## Verktøy for KI-forordningen
TADA jobber sammen med KI-gruppa i juridisk avdeling for å utvikle verktøy som kan hjelpe team med å navigere og etterleve den nye KI-forordningen.

- [Er jeg provicder eller deployer?](https://beslutt.nav.no/tree.html?id=provider-deployer)

- [Hvilket risikonivå har KI-systemet mitt?](https://beslutt.nav.no/tree.html?id=risiko)

## Verktøy og artikler

- [Beslutt](https://beslutt.nav.no/)
- [Prinsipper for ansvarlig KI i Nav](https://aksel.nav.no/god-praksis/artikler/prinsipper-for-ansvarlig-ki-i-nav)



