name: Build and deploy main
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.8.24"
      - name: Render Quarto site
        working-directory: site
        run: |
          quarto check install --no-prompt
          quarto render
      - name: Verify build exists
        run: |
          test -d site/_site && ls -la site/_site
      - uses: nais/docker-build-push@1fae4798c79f4af4c3cdbd3fe65e51f8f3ba2368
        id: docker-push
        with:
          team: tada
          push_image: true
          pull: true
      - uses: nais/deploy/actions/deploy@d30ad2c21d7862e22d45cac6accfbf42bbbc0f39
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
